/*
 * The MIT License
 *
 * Copyright 2023 Pedj.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package libsys.views;

import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import libsys.controllers.BNRWindowController;
import libsys.utils.TxtAlertHandler;

/**
 *
 * @author Pedj
 */
public class BNRWindow extends javax.swing.JFrame {

    public String borrowIDString;
    public String userIDString;
    public String bookIDString;
    public String bookNameString;
    public Integer bookQtyInteger;
    public Date bookBDate;
    public Date bookRDate;

    /**
     * Creates new form BNRWindow
     */
    public BNRWindow() {
        initComponents();
        initBNRWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BNRStatusGrpBtn = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BNRIdField1 = new javax.swing.JTextField();
        BNRIdField2 = new javax.swing.JTextField();
        BNRNameField = new javax.swing.JTextField();
        BNRQtyField = new javax.swing.JTextField();
        BNRbDate = new com.toedter.calendar.JDateChooser();
        BNRrDate = new com.toedter.calendar.JDateChooser();
        BNRBtnYes = new javax.swing.JRadioButton();
        BNRBtnNo = new javax.swing.JRadioButton();
        BNRSearchField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Apply = new javax.swing.JButton();
        Clearbtn = new javax.swing.JButton();
        ctxAlertTxt = new javax.swing.JLabel();
        BNRPkIdField = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Borrown And Return ");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 320, 460, 130);

        BNRIdField1.setEditable(false);
        BNRIdField1.setBackground(new java.awt.Color(204, 204, 204));
        BNRIdField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(BNRIdField1);
        BNRIdField1.setBounds(20, 40, 460, 30);

        BNRIdField2.setEditable(false);
        BNRIdField2.setBackground(new java.awt.Color(204, 204, 204));
        BNRIdField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        BNRIdField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(BNRIdField2);
        BNRIdField2.setBounds(20, 100, 460, 30);

        BNRNameField.setEditable(false);
        BNRNameField.setBackground(new java.awt.Color(204, 204, 204));
        BNRNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(BNRNameField);
        BNRNameField.setBounds(20, 160, 460, 30);

        BNRQtyField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BNRQtyField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(BNRQtyField);
        BNRQtyField.setBounds(20, 220, 50, 30);

        BNRbDate.setDateFormatString("yyyy-dd-MM");
        jPanel2.add(BNRbDate);
        BNRbDate.setBounds(80, 220, 140, 30);

        BNRrDate.setDateFormatString("yyyy-dd-MM");
        jPanel2.add(BNRrDate);
        BNRrDate.setBounds(230, 220, 150, 30);

        BNRStatusGrpBtn.add(BNRBtnYes);
        BNRBtnYes.setText("Yes");
        jPanel2.add(BNRBtnYes);
        BNRBtnYes.setBounds(20, 280, 50, 30);

        BNRStatusGrpBtn.add(BNRBtnNo);
        BNRBtnNo.setText("No");
        jPanel2.add(BNRBtnNo);
        BNRBtnNo.setBounds(80, 280, 60, 30);

        BNRSearchField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BNRSearchField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(BNRSearchField);
        BNRSearchField.setBounds(160, 280, 320, 30);

        jLabel1.setText("Quantity");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 200, 60, 16);

        jLabel2.setText("User ID");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 20, 60, 16);

        jLabel3.setText("Book Name");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 140, 80, 16);

        jLabel4.setText("Borrow Date");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(80, 200, 120, 16);

        jLabel5.setText("Return Date");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(230, 200, 120, 16);

        jLabel6.setText("Search:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(160, 260, 120, 16);

        jLabel7.setText("Return Status");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 260, 120, 16);

        Apply.setText("Apply");
        Apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyActionPerformed(evt);
            }
        });
        jPanel2.add(Apply);
        Apply.setBounds(390, 460, 90, 30);

        Clearbtn.setBackground(new java.awt.Color(255, 153, 153));
        Clearbtn.setText("Clear");
        Clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Clearbtn);
        Clearbtn.setBounds(390, 220, 90, 30);
        jPanel2.add(ctxAlertTxt);
        ctxAlertTxt.setBounds(20, 466, 350, 20);

        BNRPkIdField.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        BNRPkIdField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(BNRPkIdField);
        BNRPkIdField.setBounds(150, 10, 330, 20);

        jLabel9.setText("Book ID");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 80, 60, 16);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public BNRWindow(String borrowIDString, String userIDString, String bookIDString, Integer bookQtyInteger) {
        this.borrowIDString = (borrowIDString != null) ? borrowIDString : "";
        this.userIDString = (userIDString != null) ? userIDString : "";
        this.bookIDString = (bookIDString != null) ? bookIDString : "";
        this.bookQtyInteger = (bookQtyInteger != null) ? bookQtyInteger : 0;

        initComponents();
        initBNRWindow();
    }

    public BNRWindow(String borrowIDString, String userIDString, String bookIDString) {
        this.borrowIDString = (borrowIDString != null) ? borrowIDString : "";
        this.userIDString = (userIDString != null) ? userIDString : "";
        this.bookIDString = (bookIDString != null) ? bookIDString : "";

        initComponents();
        initBNRWindow();
    }

    public BNRWindow(String borrowIDString, String userIDString) {
        this.borrowIDString = (borrowIDString != null) ? borrowIDString : "";
        this.userIDString = (userIDString != null) ? userIDString : "";

        initComponents();
        initBNRWindow();
    }

    public BNRWindow(String userIDString) {
        this.userIDString = (userIDString != null) ? userIDString : "";

        initComponents();
        initBNRWindow();
    }

    private void ApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyActionPerformed
        // TODO add your handling code here:
        String id0 = BNRPkIdField.getText(); // This is the borrow ID
        String id1 = BNRIdField1.getText(); // This is the user ID
        String id2 = BNRIdField2.getText(); // This is the book id
        String qtyString = BNRQtyField.getText();
        Date bDate = BNRbDate.getDate();
        Date rDate = BNRrDate.getDate();
        Boolean BNRStats = BNRBtnYes.isSelected();

        // Validate input
        if (id1.isEmpty() || id2.isEmpty() || qtyString.isEmpty() || bDate == null || rDate == null) {
            TxtAlertHandler.setJLabel(ctxAlertTxt, "WARNING", "Please fill in all the fields.", true);
            return;
        }

        // Convert qtyString to integer
        int qty;
        try {
            qty = Integer.parseInt(qtyString);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid quantity.", "Invalid Quantity", JOptionPane.WARNING_MESSAGE);
            TxtAlertHandler.setJLabel(ctxAlertTxt, "WARNING", "Please enter a valid quantity.", false);
            return;
        }

        try {
            if (id0 == null || id0.isEmpty()) {
                // If borrowID is empty, call addToMySQLBorrow to add a new record
                BNRWindowController.addToMySQLBorrow(id1, id2, qty, bDate, rDate, BNRStats);
            } else {
                // If borrowID is not empty, call updateToMySQLBorrow to update the existing record
                BNRWindowController.updateToMySQLBorrow(id0, id1, id2, qty, bDate, rDate, BNRStats);
            }
            TxtAlertHandler.setJLabel(ctxAlertTxt, "SUCCESS", "Borrow record processed successfully.", true);
        } catch (SQLException ex) {
            Logger.getLogger(BNRWindow.class.getName()).log(Level.SEVERE, null, ex);
            TxtAlertHandler.setJLabel(ctxAlertTxt, "ERROE", "Something went wrong.", true);
        }

        this.dispose();
    }//GEN-LAST:event_ApplyActionPerformed

    private void ClearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearbtnActionPerformed
        // TODO add your handling code here:
        if (BNRIdField1.isEditable()) {
            BNRIdField1.setText("");
        }
        BNRIdField2.setText("");
        BNRNameField.setText("");
        BNRQtyField.setText("");

        // Set the dates to the current date in year-month-date format
        Date currentDate = new Date();
        BNRbDate.setDate(currentDate);
        BNRrDate.setDate(currentDate);

        TxtAlertHandler.setJLabel(ctxAlertTxt, "SUCCESS", "CLEARED!", true);

    }//GEN-LAST:event_ClearbtnActionPerformed

    public void initBNRWindow() {
        if (userIDString != null) {
            BNRPkIdField.setText(borrowIDString);
            BNRIdField1.setText(userIDString);
            BNRIdField2.setText(bookIDString);
        } else {
            BNRPkIdField.setText("");
            BNRIdField1.setText("");
            BNRIdField2.setText("");
        }

        // Set BNRbDate to current date if it is null
        if (BNRbDate.getDate() == null) {
            BNRbDate.setDate(Calendar.getInstance().getTime());
        }

        // Enable BNRBtnYes if it is not selected
        if (!BNRBtnYes.isSelected()) {
            BNRBtnYes.setEnabled(true);
        }

        BNRWindowController.loadBNRWindowTable1(jScrollPane1);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BNRWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BNRWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BNRWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BNRWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BNRWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apply;
    public static javax.swing.JRadioButton BNRBtnNo;
    public static javax.swing.JRadioButton BNRBtnYes;
    public static javax.swing.JTextField BNRIdField1;
    public static javax.swing.JTextField BNRIdField2;
    public static javax.swing.JTextField BNRNameField;
    public static javax.swing.JLabel BNRPkIdField;
    public static javax.swing.JTextField BNRQtyField;
    public static javax.swing.JTextField BNRSearchField;
    private javax.swing.ButtonGroup BNRStatusGrpBtn;
    private com.toedter.calendar.JDateChooser BNRbDate;
    private com.toedter.calendar.JDateChooser BNRrDate;
    private javax.swing.JButton Clearbtn;
    private javax.swing.JLabel ctxAlertTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
