/*
 * The MIT License
 *
 * Copyright 2023 Pedj.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package libsys.views;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import libsys.controllers.DBWin1Controller;
import libsys.controllers.DBWin2Controller;
import libsys.controllers.DBWin3Controller;
import libsys.utils.LibUtils;
import libsys.utils.Styles;
import libsys.utils.TxtAlertHandler;
import org.kordamp.ikonli.materialdesign.MaterialDesign;
import org.kordamp.ikonli.swing.FontIcon;

/**
 *
 * @author Pedj
 */
public class Dashboard extends javax.swing.JFrame {

    Color pColor = Styles.ctxColors("primary");
    Color sColor2 = Styles.ctxColors("secondary2");

    FontIcon dbIcon1 = FontIcon.of(MaterialDesign.MDI_CLIPBOARD_ACCOUNT);
    FontIcon dbIcon2 = FontIcon.of(MaterialDesign.MDI_CLIPBOARD);
    FontIcon dbIcon3 = FontIcon.of(MaterialDesign.MDI_ACCOUNT);
    FontIcon dbIcon4 = FontIcon.of(MaterialDesign.MDI_NUMERIC_5_BOX_MULTIPLE_OUTLINE);
    FontIcon dbIcon5 = FontIcon.of(MaterialDesign.MDI_BELL);
    FontIcon dbIcon6 = FontIcon.of(MaterialDesign.MDI_WRENCH);
    FontIcon dbIcon7 = FontIcon.of(MaterialDesign.MDI_LOGOUT_VARIANT);

    public static String BNRBorrowID;

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        prepareIcons();
        initWin1();
        initWin2();
        initWin3();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BNRStatusRadioGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dbLabel1 = new javax.swing.JLabel();
        dbLabel2 = new javax.swing.JLabel();
        dbLabel3 = new javax.swing.JLabel();
        dbLabel4 = new javax.swing.JLabel();
        dbLabel5 = new javax.swing.JLabel();
        dbLabel6 = new javax.swing.JLabel();
        dbLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        winTab1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        catalogIDField = new javax.swing.JTextField();
        bookNameField = new javax.swing.JTextField();
        bookAuthorField = new javax.swing.JTextField();
        bookPubField = new javax.swing.JTextField();
        bookQtyField = new javax.swing.JTextField();
        bookSearchField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        catalogAddBtn = new javax.swing.JButton();
        catalogUpBtn1 = new javax.swing.JButton();
        catalogRefBtn = new javax.swing.JButton();
        catalogDelBtn = new javax.swing.JButton();
        catalogClrBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        winTab2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BNRTable = new javax.swing.JTable();
        BNRUserIdField1 = new javax.swing.JTextField();
        BNRBookIdField2 = new javax.swing.JTextField();
        BNRNameField = new javax.swing.JTextField();
        BNRQtyField = new javax.swing.JTextField();
        BNRAmountField = new javax.swing.JTextField();
        BNRSearchField2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BNRDelBtn = new javax.swing.JButton();
        BNRClearBtn1 = new javax.swing.JButton();
        BNREditBtn = new javax.swing.JButton();
        BNRRefBtn1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        winTab3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        USERidField = new javax.swing.JTextField();
        USERnameField = new javax.swing.JTextField();
        USERemailField = new javax.swing.JTextField();
        USERsearchField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        USERopenBtn = new javax.swing.JButton();
        USERopenBtn1 = new javax.swing.JButton();
        USERopenBtn2 = new javax.swing.JButton();
        USERopenBtn3 = new javax.swing.JButton();
        USERopenBtn4 = new javax.swing.JButton();
        USERopenBtn5 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        winTab4 = new javax.swing.JPanel();
        winTab5 = new javax.swing.JPanel();
        winTab6 = new javax.swing.JPanel();
        ctxTxtAlert = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LibSys > Dashboard");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(75, 0, 130));

        dbLabel1.setBackground(new java.awt.Color(75, 0, 130));
        dbLabel1.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        dbLabel1.setForeground(new java.awt.Color(255, 255, 255));
        dbLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dbLabel1.setText("Catalog");
        dbLabel1.setToolTipText(null);
        dbLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        dbLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dbLabel1.setFocusCycleRoot(true);
        dbLabel1.setFocusTraversalPolicy(null);
        dbLabel1.setOpaque(true);
        dbLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dbLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dbLabel1MouseExited(evt);
            }
        });

        dbLabel2.setBackground(new java.awt.Color(75, 0, 130));
        dbLabel2.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        dbLabel2.setForeground(new java.awt.Color(255, 255, 255));
        dbLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dbLabel2.setText("Borrow And Return");
        dbLabel2.setToolTipText(null);
        dbLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        dbLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dbLabel2.setFocusable(false);
        dbLabel2.setOpaque(true);
        dbLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dbLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dbLabel2MouseExited(evt);
            }
        });

        dbLabel3.setBackground(new java.awt.Color(75, 0, 130));
        dbLabel3.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        dbLabel3.setForeground(new java.awt.Color(255, 255, 255));
        dbLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dbLabel3.setText("Users");
        dbLabel3.setToolTipText(null);
        dbLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        dbLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dbLabel3.setFocusable(false);
        dbLabel3.setOpaque(true);
        dbLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dbLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dbLabel3MouseExited(evt);
            }
        });

        dbLabel4.setBackground(new java.awt.Color(75, 0, 130));
        dbLabel4.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        dbLabel4.setForeground(new java.awt.Color(255, 255, 255));
        dbLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dbLabel4.setText("Inventory");
        dbLabel4.setToolTipText(null);
        dbLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        dbLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dbLabel4.setFocusable(false);
        dbLabel4.setOpaque(true);
        dbLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dbLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dbLabel4MouseExited(evt);
            }
        });

        dbLabel5.setBackground(new java.awt.Color(75, 0, 130));
        dbLabel5.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        dbLabel5.setForeground(new java.awt.Color(255, 255, 255));
        dbLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dbLabel5.setText("Notifications");
        dbLabel5.setToolTipText(null);
        dbLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        dbLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dbLabel5.setFocusable(false);
        dbLabel5.setOpaque(true);
        dbLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dbLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dbLabel5MouseExited(evt);
            }
        });

        dbLabel6.setBackground(new java.awt.Color(75, 0, 130));
        dbLabel6.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        dbLabel6.setForeground(new java.awt.Color(255, 255, 255));
        dbLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dbLabel6.setText("Settings");
        dbLabel6.setToolTipText(null);
        dbLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        dbLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dbLabel6.setFocusable(false);
        dbLabel6.setOpaque(true);
        dbLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dbLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dbLabel6MouseExited(evt);
            }
        });

        dbLabel7.setBackground(new java.awt.Color(75, 0, 130));
        dbLabel7.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        dbLabel7.setForeground(new java.awt.Color(255, 255, 255));
        dbLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dbLabel7.setText("Sign Out");
        dbLabel7.setToolTipText(null);
        dbLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        dbLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dbLabel7.setFocusable(false);
        dbLabel7.setOpaque(true);
        dbLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dbLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dbLabel7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dbLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(dbLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(dbLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dbLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dbLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dbLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dbLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(dbLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dbLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dbLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dbLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dbLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dbLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dbLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dbLabel2, dbLabel3, dbLabel4, dbLabel5, dbLabel6});

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 550));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        winTab1.setBackground(new java.awt.Color(255, 255, 255));
        winTab1.setLayout(null);

        jTable1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        winTab1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 320, 780, 200);

        catalogIDField.setEditable(false);
        catalogIDField.setBackground(new java.awt.Color(204, 204, 204));
        catalogIDField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        catalogIDField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        winTab1.add(catalogIDField);
        catalogIDField.setBounds(10, 40, 630, 35);

        bookNameField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bookNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        winTab1.add(bookNameField);
        bookNameField.setBounds(10, 110, 510, 35);

        bookAuthorField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bookAuthorField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        winTab1.add(bookAuthorField);
        bookAuthorField.setBounds(10, 180, 510, 35);

        bookPubField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bookPubField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookPubField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        winTab1.add(bookPubField);
        bookPubField.setBounds(530, 110, 110, 35);

        bookQtyField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bookQtyField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookQtyField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        winTab1.add(bookQtyField);
        bookQtyField.setBounds(530, 180, 110, 35);

        bookSearchField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bookSearchField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookSearchField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        bookSearchField.setName(""); // NOI18N
        winTab1.add(bookSearchField);
        bookSearchField.setBounds(10, 280, 630, 35);

        jLabel2.setText("Book ID");
        winTab1.add(jLabel2);
        jLabel2.setBounds(10, 20, 70, 16);

        jLabel3.setText("Book Name");
        winTab1.add(jLabel3);
        jLabel3.setBounds(10, 90, 272, 16);

        jLabel4.setText("Author");
        winTab1.add(jLabel4);
        jLabel4.setBounds(10, 160, 272, 16);

        jLabel5.setText("Quantity");
        winTab1.add(jLabel5);
        jLabel5.setBounds(530, 160, 63, 16);

        jLabel6.setText("Publication");
        winTab1.add(jLabel6);
        jLabel6.setBounds(530, 90, 60, 16);

        jLabel7.setText("Search");
        winTab1.add(jLabel7);
        jLabel7.setBounds(10, 260, 63, 16);

        catalogAddBtn.setBackground(new java.awt.Color(153, 255, 153));
        catalogAddBtn.setText("Add");
        catalogAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogAddBtnActionPerformed(evt);
            }
        });
        winTab1.add(catalogAddBtn);
        catalogAddBtn.setBounds(650, 40, 140, 35);

        catalogUpBtn1.setBackground(new java.awt.Color(153, 153, 255));
        catalogUpBtn1.setText("Update");
        catalogUpBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogUpBtn1ActionPerformed(evt);
            }
        });
        winTab1.add(catalogUpBtn1);
        catalogUpBtn1.setBounds(650, 80, 140, 35);

        catalogRefBtn.setBackground(new java.awt.Color(255, 255, 153));
        catalogRefBtn.setText("Refresh");
        catalogRefBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogRefBtnActionPerformed(evt);
            }
        });
        winTab1.add(catalogRefBtn);
        catalogRefBtn.setBounds(650, 120, 140, 35);

        catalogDelBtn.setBackground(new java.awt.Color(255, 153, 153));
        catalogDelBtn.setText("Delete");
        catalogDelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogDelBtnActionPerformed(evt);
            }
        });
        winTab1.add(catalogDelBtn);
        catalogDelBtn.setBounds(650, 180, 140, 35);

        catalogClrBtn.setText("Clear");
        catalogClrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogClrBtnActionPerformed(evt);
            }
        });
        winTab1.add(catalogClrBtn);
        catalogClrBtn.setBounds(650, 280, 140, 36);

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel1.setText("CATALOG");
        winTab1.add(jLabel1);
        jLabel1.setBounds(320, 10, 91, 22);

        jTabbedPane1.addTab("tab1", winTab1);

        winTab2.setBackground(new java.awt.Color(255, 255, 255));
        winTab2.setLayout(null);

        BNRTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(BNRTable);

        winTab2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 320, 780, 200);

        BNRUserIdField1.setEditable(false);
        BNRUserIdField1.setBackground(new java.awt.Color(204, 204, 204));
        BNRUserIdField1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BNRUserIdField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BNRUserIdField1.setName(""); // NOI18N
        winTab2.add(BNRUserIdField1);
        BNRUserIdField1.setBounds(10, 40, 630, 35);

        BNRBookIdField2.setEditable(false);
        BNRBookIdField2.setBackground(new java.awt.Color(204, 204, 204));
        BNRBookIdField2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BNRBookIdField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BNRBookIdField2.setName(""); // NOI18N
        winTab2.add(BNRBookIdField2);
        BNRBookIdField2.setBounds(10, 110, 630, 36);

        BNRNameField.setEditable(false);
        BNRNameField.setBackground(new java.awt.Color(204, 204, 204));
        BNRNameField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BNRNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BNRNameField.setName(""); // NOI18N
        winTab2.add(BNRNameField);
        BNRNameField.setBounds(10, 180, 260, 35);

        BNRQtyField.setEditable(false);
        BNRQtyField.setBackground(new java.awt.Color(204, 204, 204));
        BNRQtyField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BNRQtyField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BNRQtyField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BNRQtyField.setName(""); // NOI18N
        winTab2.add(BNRQtyField);
        BNRQtyField.setBounds(280, 180, 100, 35);

        BNRAmountField.setEditable(false);
        BNRAmountField.setBackground(new java.awt.Color(204, 204, 204));
        BNRAmountField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BNRAmountField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BNRAmountField.setName(""); // NOI18N
        winTab2.add(BNRAmountField);
        BNRAmountField.setBounds(390, 180, 250, 36);

        BNRSearchField2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BNRSearchField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BNRSearchField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BNRSearchField2.setName(""); // NOI18N
        winTab2.add(BNRSearchField2);
        BNRSearchField2.setBounds(10, 280, 630, 35);

        jLabel13.setText("User ID");
        winTab2.add(jLabel13);
        jLabel13.setBounds(10, 20, 63, 16);

        jLabel12.setText("Book ID");
        winTab2.add(jLabel12);
        jLabel12.setBounds(10, 90, 63, 16);

        jLabel9.setText("Quantity");
        winTab2.add(jLabel9);
        jLabel9.setBounds(280, 160, 63, 16);

        jLabel8.setText("Calculated Amount:");
        winTab2.add(jLabel8);
        jLabel8.setBounds(390, 160, 120, 16);

        BNRDelBtn.setBackground(new java.awt.Color(255, 153, 153));
        BNRDelBtn.setText("Delete");
        BNRDelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNRDelBtnActionPerformed(evt);
            }
        });
        winTab2.add(BNRDelBtn);
        BNRDelBtn.setBounds(650, 180, 140, 36);

        BNRClearBtn1.setText("Clear");
        BNRClearBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNRClearBtn1ActionPerformed(evt);
            }
        });
        winTab2.add(BNRClearBtn1);
        BNRClearBtn1.setBounds(651, 280, 140, 36);

        BNREditBtn.setBackground(new java.awt.Color(153, 153, 255));
        BNREditBtn.setText("Edit");
        BNREditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNREditBtnActionPerformed(evt);
            }
        });
        winTab2.add(BNREditBtn);
        BNREditBtn.setBounds(650, 80, 140, 36);

        BNRRefBtn1.setBackground(new java.awt.Color(255, 255, 153));
        BNRRefBtn1.setText("Refresh");
        BNRRefBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNRRefBtn1ActionPerformed(evt);
            }
        });
        winTab2.add(BNRRefBtn1);
        BNRRefBtn1.setBounds(650, 120, 140, 36);

        jLabel15.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel15.setText("Borrow And Return");
        winTab2.add(jLabel15);
        jLabel15.setBounds(280, 10, 200, 22);

        jLabel21.setText("Search");
        winTab2.add(jLabel21);
        jLabel21.setBounds(10, 260, 63, 16);

        jLabel10.setText("Book Name");
        winTab2.add(jLabel10);
        jLabel10.setBounds(10, 160, 110, 16);

        jTabbedPane1.addTab("tab2", winTab2);

        winTab3.setBackground(new java.awt.Color(255, 255, 255));
        winTab3.setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable2);

        winTab3.add(jScrollPane3);
        jScrollPane3.setBounds(10, 230, 630, 290);

        USERidField.setEditable(false);
        USERidField.setBackground(new java.awt.Color(204, 204, 204));
        USERidField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        USERidField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        USERidField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        USERidField.setName(""); // NOI18N
        winTab3.add(USERidField);
        USERidField.setBounds(10, 40, 630, 35);

        USERnameField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        USERnameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        USERnameField.setName(""); // NOI18N
        winTab3.add(USERnameField);
        USERnameField.setBounds(10, 110, 360, 35);

        USERemailField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        USERemailField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        USERemailField.setName(""); // NOI18N
        winTab3.add(USERemailField);
        USERemailField.setBounds(380, 110, 260, 35);

        USERsearchField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        USERsearchField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        USERsearchField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        USERsearchField.setName(""); // NOI18N
        winTab3.add(USERsearchField);
        USERsearchField.setBounds(10, 180, 630, 35);

        jLabel16.setText("Email");
        winTab3.add(jLabel16);
        jLabel16.setBounds(380, 90, 43, 16);

        jLabel18.setText("Search");
        winTab3.add(jLabel18);
        jLabel18.setBounds(10, 160, 43, 16);

        jLabel17.setText("User ID");
        winTab3.add(jLabel17);
        jLabel17.setBounds(10, 20, 50, 16);

        jLabel19.setText("Name");
        winTab3.add(jLabel19);
        jLabel19.setBounds(10, 90, 43, 16);

        USERopenBtn.setBackground(new java.awt.Color(153, 255, 255));
        USERopenBtn.setText("Open User Info");
        USERopenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERopenBtnActionPerformed(evt);
            }
        });
        winTab3.add(USERopenBtn);
        USERopenBtn.setBounds(650, 40, 140, 36);

        USERopenBtn1.setBackground(new java.awt.Color(153, 255, 153));
        USERopenBtn1.setText("Add");
        USERopenBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERopenBtn1ActionPerformed(evt);
            }
        });
        winTab3.add(USERopenBtn1);
        USERopenBtn1.setBounds(650, 80, 140, 36);

        USERopenBtn2.setBackground(new java.awt.Color(153, 153, 255));
        USERopenBtn2.setText("Update User");
        USERopenBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERopenBtn2ActionPerformed(evt);
            }
        });
        winTab3.add(USERopenBtn2);
        USERopenBtn2.setBounds(650, 120, 140, 36);

        USERopenBtn3.setBackground(new java.awt.Color(255, 153, 153));
        USERopenBtn3.setText("Delete");
        USERopenBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERopenBtn3ActionPerformed(evt);
            }
        });
        winTab3.add(USERopenBtn3);
        USERopenBtn3.setBounds(650, 280, 140, 36);

        USERopenBtn4.setBackground(new java.awt.Color(255, 255, 153));
        USERopenBtn4.setText("Refresh");
        USERopenBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERopenBtn4ActionPerformed(evt);
            }
        });
        winTab3.add(USERopenBtn4);
        USERopenBtn4.setBounds(650, 180, 140, 36);

        USERopenBtn5.setText("Clear");
        USERopenBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERopenBtn5ActionPerformed(evt);
            }
        });
        winTab3.add(USERopenBtn5);
        USERopenBtn5.setBounds(650, 480, 140, 36);

        jLabel20.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel20.setText("User Management");
        winTab3.add(jLabel20);
        jLabel20.setBounds(290, 10, 170, 22);

        jTabbedPane1.addTab("tab3", winTab3);

        winTab4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout winTab4Layout = new javax.swing.GroupLayout(winTab4);
        winTab4.setLayout(winTab4Layout);
        winTab4Layout.setHorizontalGroup(
            winTab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        winTab4Layout.setVerticalGroup(
            winTab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", winTab4);

        winTab5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout winTab5Layout = new javax.swing.GroupLayout(winTab5);
        winTab5.setLayout(winTab5Layout);
        winTab5Layout.setHorizontalGroup(
            winTab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        winTab5Layout.setVerticalGroup(
            winTab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab5", winTab5);

        winTab6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout winTab6Layout = new javax.swing.GroupLayout(winTab6);
        winTab6.setLayout(winTab6Layout);
        winTab6Layout.setHorizontalGroup(
            winTab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        winTab6Layout.setVerticalGroup(
            winTab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab6", winTab6);

        jPanel3.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 800, 560));

        ctxTxtAlert.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        ctxTxtAlert.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.add(ctxTxtAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 800, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 800, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void prepareIcons() {
        dbLabel1.setIcon(dbIcon1);
        dbLabel1.setIconTextGap(5);
        dbIcon1.setIconSize(15);
        dbIcon1.setIconColor(Color.WHITE);

        dbLabel2.setIcon(dbIcon2);
        dbLabel2.setIconTextGap(5);
        dbIcon2.setIconSize(15);
        dbIcon2.setIconColor(Color.WHITE);

        dbLabel3.setIcon(dbIcon3);
        dbLabel3.setIconTextGap(5);
        dbIcon3.setIconSize(15);
        dbIcon3.setIconColor(Color.WHITE);

        dbLabel4.setIcon(dbIcon4);
        dbLabel4.setIconTextGap(5);
        dbIcon4.setIconSize(15);
        dbIcon4.setIconColor(Color.WHITE);

        dbLabel5.setIcon(dbIcon5);
        dbLabel5.setIconTextGap(5);
        dbIcon5.setIconSize(15);
        dbIcon5.setIconColor(Color.WHITE);

        dbLabel6.setIcon(dbIcon6);
        dbLabel6.setIconTextGap(5);
        dbIcon6.setIconSize(15);
        dbIcon6.setIconColor(Color.WHITE);

        dbLabel7.setIcon(dbIcon7);
        dbLabel7.setIconTextGap(5);
        dbIcon7.setIconSize(15);
        dbIcon7.setIconColor(Color.WHITE);

    }

    private void isEntered(JLabel label) {
        label.setBackground(sColor2);
        label.setForeground(Color.BLACK);
    }

    private void isExited(JLabel label) {
        label.setBackground(pColor);
        label.setForeground(Color.WHITE);
    }

    public void initWin1() {
        DBWin1Controller.loadCatalogTable(jScrollPane1);
        LibUtils.numOnlyTextField(bookQtyField);
        LibUtils.numOnlyTextField(bookPubField);
    }

    public void initWin2() {
        DBWin2Controller.loadBNRTable(jScrollPane2);
    }

    public void initWin3() {
        DBWin3Controller.loadUserTable(jScrollPane3);
    }

//
//    Notes: I hate everything below this part. Seriously, What a mess.
//
    private void dbLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabel1MouseEntered
        // TODO add your handling code here:
        isEntered(dbLabel1);
    }//GEN-LAST:event_dbLabel1MouseEntered

    private void dbLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabel1MouseExited
        // TODO add your handling code here:
        isExited(dbLabel1);
    }//GEN-LAST:event_dbLabel1MouseExited

    private void dbLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabel2MouseEntered
        // TODO add your handling code here:
        isEntered(dbLabel2);
    }//GEN-LAST:event_dbLabel2MouseEntered

    private void dbLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabel2MouseExited
        // TODO add your handling code here:
        isExited(dbLabel2);
    }//GEN-LAST:event_dbLabel2MouseExited

    private void dbLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabel3MouseEntered
        // TODO add your handling code here:
        isEntered(dbLabel3);
    }//GEN-LAST:event_dbLabel3MouseEntered

    private void dbLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabel3MouseExited
        // TODO add your handling code here:
        isExited(dbLabel3);
    }//GEN-LAST:event_dbLabel3MouseExited

    private void dbLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabel4MouseEntered
        // TODO add your handling code here:
        isEntered(dbLabel4);
    }//GEN-LAST:event_dbLabel4MouseEntered

    private void dbLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabel4MouseExited
        // TODO add your handling code here:
        isExited(dbLabel4);
    }//GEN-LAST:event_dbLabel4MouseExited

    private void dbLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabel5MouseExited
        // TODO add your handling code here:
        isExited(dbLabel5);
    }//GEN-LAST:event_dbLabel5MouseExited

    private void dbLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabel5MouseEntered
        // TODO add your handling code here:
        isEntered(dbLabel5);
    }//GEN-LAST:event_dbLabel5MouseEntered

    private void dbLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabel6MouseExited
        // TODO add your handling code here:
        isExited(dbLabel6);
    }//GEN-LAST:event_dbLabel6MouseExited

    private void dbLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabel6MouseEntered
        // TODO add your handling code here:
        isEntered(dbLabel6);
    }//GEN-LAST:event_dbLabel6MouseEntered

    private void dbLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabel1MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_dbLabel1MouseClicked

    private void dbLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabel2MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);

    }//GEN-LAST:event_dbLabel2MouseClicked

    private void dbLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabel3MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);

    }//GEN-LAST:event_dbLabel3MouseClicked

    private void dbLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabel4MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);

    }//GEN-LAST:event_dbLabel4MouseClicked

    private void dbLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabel5MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);

    }//GEN-LAST:event_dbLabel5MouseClicked

    private void dbLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabel6MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);

    }//GEN-LAST:event_dbLabel6MouseClicked

    private void dbLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabel7MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Login login = new Login();
        login.setVisible(true);
//            Login dashboard = new Dashboard();
//            dashboard.setVisible(true);

    }//GEN-LAST:event_dbLabel7MouseClicked

    private void dbLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabel7MouseEntered
        // TODO add your handling code here:
        isEntered(dbLabel7);

    }//GEN-LAST:event_dbLabel7MouseEntered

    private void dbLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabel7MouseExited
        // TODO add your handling code here:
        isExited(dbLabel7);
    }//GEN-LAST:event_dbLabel7MouseExited

    private void catalogAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogAddBtnActionPerformed
        // TODO add your handling code here:
        String id = catalogIDField.getText();
        String name = bookNameField.getText();
        String author = bookAuthorField.getText();
        String qtyText = bookQtyField.getText();
        String pubText = bookPubField.getText();

        if (name.isEmpty() || author.isEmpty() || qtyText.isEmpty() || pubText.isEmpty()) {
            TxtAlertHandler.setJLabel(ctxTxtAlert, "ERROR", "Please fill all fields!", true);
            return;
        }

        Integer qty = Integer.valueOf(qtyText);
        Integer pub = Integer.valueOf(pubText);
        DBWin1Controller.addToMySQLBooks(id, name, author, qty, pub);

    }//GEN-LAST:event_catalogAddBtnActionPerformed

    private void catalogClrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogClrBtnActionPerformed
        // TODO add your handling code here:
        catalogIDField.setText("");
        bookAuthorField.setText("");
        bookNameField.setText("");
        bookPubField.setText("");
        bookQtyField.setText("");
        TxtAlertHandler.setJLabel(ctxTxtAlert, "SUCCESS", "CLEARED!", true);

    }//GEN-LAST:event_catalogClrBtnActionPerformed

    private void catalogRefBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogRefBtnActionPerformed
        // TODO add your handling code here:
        DBWin1Controller.refreshTableModel(jScrollPane1);
        TxtAlertHandler.setJLabel(ctxTxtAlert, "SUCCESS", "REFRESHED!", true);
    }//GEN-LAST:event_catalogRefBtnActionPerformed

    private void catalogDelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogDelBtnActionPerformed
        // TODO add your handling code here:
        String id = catalogIDField.getText();
        if (id.isEmpty()) {
            TxtAlertHandler.setJLabel(ctxTxtAlert, "Error", "Please select a row from the table first!", true);
            return;
        }
        DBWin1Controller.deleteFromMySQLBooks(id);
        TxtAlertHandler.setJLabel(ctxTxtAlert, "SUCCESS", "DELETED!", true);

    }//GEN-LAST:event_catalogDelBtnActionPerformed

    private void catalogUpBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogUpBtn1ActionPerformed
        // TODO add your handling code here:
        String id = catalogIDField.getText();
        String name = bookNameField.getText();
        String author = bookAuthorField.getText();
        String qtyText = bookQtyField.getText();
        String pubText = bookPubField.getText();
        if (id.isEmpty()) {
            TxtAlertHandler.setJLabel(ctxTxtAlert, "Error", "Please select a row from the table first!", true);
            return;
        }

        if (name.isEmpty() || author.isEmpty() || qtyText.isEmpty() || pubText.isEmpty()) {
            TxtAlertHandler.setJLabel(ctxTxtAlert, "ERROR", "Please fill all fields!", true);
            return;
        }
        Integer qty = Integer.valueOf(qtyText);
        Integer pub = Integer.valueOf(pubText);
        DBWin1Controller.updateToMySQLBooks(id, name, author, qty, pub);
//        TxtAlertHandler.setJLabel(ctxTxtAlert, "SUCCESS", "UPDATED!", true);

    }//GEN-LAST:event_catalogUpBtn1ActionPerformed

    private void BNRDelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNRDelBtnActionPerformed
        // TODO add your handling code here:
        String id = BNRBorrowID.toString();

        if (id.isEmpty()) {
            TxtAlertHandler.setJLabel(ctxTxtAlert, "Warning", "Please select from the row!", true);
            return;
        }
        DBWin2Controller.deleteFromBorrowRecords(BNRBorrowID);
//        DBWin2Controller.deleteFromBorrowRecords(bookId, userId);
//        DBWin2Controller.loadBNRTable(jScrollPane1);

    }//GEN-LAST:event_BNRDelBtnActionPerformed

    private void BNRClearBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNRClearBtn1ActionPerformed
        // TODO add your handling code here:
        BNRUserIdField1.setText("");
        BNRBookIdField2.setText("");
        BNRNameField.setText("");
        BNRAmountField.setText("");
        BNRQtyField.setText("");

        TxtAlertHandler.setJLabel(ctxTxtAlert, "SUCCESS", "CLEARED!", true);

    }//GEN-LAST:event_BNRClearBtn1ActionPerformed

    private void BNREditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNREditBtnActionPerformed
        // TODO add your handling code here:
        String borrowID = BNRBorrowID;
        String userID = BNRUserIdField1.getText();
        String bookID = BNRBookIdField2.getText();
        Integer qty = Integer.parseInt(BNRQtyField.getText());

        if (userID.isEmpty() || bookID.isEmpty()) {
            TxtAlertHandler.setJLabel(ctxTxtAlert, "WARNING", "Select from the table first!", true);
            return;
        }
        BNRWindow bnrw1 = new BNRWindow(borrowID, userID, bookID, qty);
        bnrw1.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        bnrw1.setVisible(true);
    }//GEN-LAST:event_BNREditBtnActionPerformed

    private void BNRRefBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNRRefBtn1ActionPerformed
        // TODO add your handling code here:
        DBWin2Controller.loadBNRTable(jScrollPane2);
        TxtAlertHandler.setJLabel(ctxTxtAlert, "SUCCESS", "Table Refreshed!!", Boolean.TRUE);
    }//GEN-LAST:event_BNRRefBtn1ActionPerformed

    private void USERopenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERopenBtnActionPerformed
        String userId = USERidField.getText().trim();
        String userName = USERnameField.getText().trim();
        String userEmail = USERemailField.getText().trim();

        if (userId.isEmpty() || userName.isEmpty() || userEmail.isEmpty()) {
            TxtAlertHandler.setJLabel(ctxTxtAlert, "WARNING", "Please select a user from the table!", true);
            return;
        }

        if (!DBWin3Controller.userExists(userId)) {
            TxtAlertHandler.setJLabel(ctxTxtAlert, "WARNING", "User does not exist!", true);
            return;
        }

        UserInfo userInfoW = new UserInfo(userId, userName, userEmail);
        userInfoW.setVisible(true);
        userInfoW.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_USERopenBtnActionPerformed

    private void USERopenBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERopenBtn1ActionPerformed
        // TODO add your handling code here:
        String uID = "";
        String uName = USERnameField.getText();
        String uEmail = USERemailField.getText();

        if (uName.isEmpty() || uEmail.isEmpty()) {
            TxtAlertHandler.setJLabel(ctxTxtAlert, "SUCCESS", "Please fill all fields!", true);
            return;
        }

        // Check if the email has a valid format
        String emailRegex = "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
        if (!uEmail.matches(emailRegex)) {
            TxtAlertHandler.setJLabel(ctxTxtAlert, "WARNING", "Invalid Email Format.", true);
            return;
        }

        try {
            DBWin3Controller.addToMySQLUsers(uID, uName, uEmail);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            TxtAlertHandler.setJLabel(ctxTxtAlert, "ERROR", "Something went wrong.", true);
        }
    }//GEN-LAST:event_USERopenBtn1ActionPerformed

    private void USERopenBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERopenBtn2ActionPerformed
        // TODO add your handling code here:
        String uID = USERidField.getText();
        String uName = USERnameField.getText();
        String uEmail = USERemailField.getText();

        if (uName.isEmpty() || uEmail.isEmpty()) {
            TxtAlertHandler.setJLabel(ctxTxtAlert, "SUCCESS", "Please fill all fields!", true);
            return;
        }

        // Check if the email has a valid format
        String emailRegex = "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
        if (!uEmail.matches(emailRegex)) {
            TxtAlertHandler.setJLabel(ctxTxtAlert, "WARNING", "Invalid Email Format.", true);
            return;
        }

        try {
            DBWin3Controller.addToMySQLUsers(uID, uName, uEmail);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            TxtAlertHandler.setJLabel(ctxTxtAlert, "ERROR", "Something went wrong.", true);
        }
    }//GEN-LAST:event_USERopenBtn2ActionPerformed

    private void USERopenBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERopenBtn3ActionPerformed
        // TODO add your handling code here:

        String userId = USERidField.getText();
        if (userId.isEmpty()) {
            TxtAlertHandler.setJLabel(ctxTxtAlert, "Error", "Please select a row from the table first!", true);
            return;
        }
        try {
            DBWin3Controller.deleteToMySQLUsers(userId);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_USERopenBtn3ActionPerformed

    private void USERopenBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERopenBtn4ActionPerformed
        // TODO add your handling code here:
        DBWin3Controller.refreshTableModel(jScrollPane3);
        TxtAlertHandler.setJLabel(ctxTxtAlert, "Success", "Table Refreshed!", true);
    }//GEN-LAST:event_USERopenBtn4ActionPerformed

    private void USERopenBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERopenBtn5ActionPerformed
        // TODO add your handling code here:
        USERidField.setText("");
        USERnameField.setText("");
        USERemailField.setText("");
        TxtAlertHandler.setJLabel(ctxTxtAlert, "Success", "Cleared", true);
    }//GEN-LAST:event_USERopenBtn5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField BNRAmountField;
    public static javax.swing.JTextField BNRBookIdField2;
    public static javax.swing.JButton BNRClearBtn1;
    public static javax.swing.JButton BNRDelBtn;
    public static javax.swing.JButton BNREditBtn;
    public static javax.swing.JTextField BNRNameField;
    public static javax.swing.JTextField BNRQtyField;
    public static javax.swing.JButton BNRRefBtn1;
    public static javax.swing.JTextField BNRSearchField2;
    private javax.swing.ButtonGroup BNRStatusRadioGroup;
    private javax.swing.JTable BNRTable;
    public static javax.swing.JTextField BNRUserIdField1;
    public static javax.swing.JTextField USERemailField;
    public static javax.swing.JTextField USERidField;
    public static javax.swing.JTextField USERnameField;
    public static javax.swing.JButton USERopenBtn;
    public static javax.swing.JButton USERopenBtn1;
    public static javax.swing.JButton USERopenBtn2;
    public static javax.swing.JButton USERopenBtn3;
    public static javax.swing.JButton USERopenBtn4;
    public static javax.swing.JButton USERopenBtn5;
    public static javax.swing.JTextField USERsearchField;
    public static javax.swing.JTextField bookAuthorField;
    public static javax.swing.JTextField bookNameField;
    public static javax.swing.JTextField bookPubField;
    public static javax.swing.JTextField bookQtyField;
    public static javax.swing.JTextField bookSearchField;
    public static javax.swing.JButton catalogAddBtn;
    public static javax.swing.JButton catalogClrBtn;
    public static javax.swing.JButton catalogDelBtn;
    public static javax.swing.JTextField catalogIDField;
    public static javax.swing.JButton catalogRefBtn;
    public static javax.swing.JButton catalogUpBtn1;
    private javax.swing.JLabel ctxTxtAlert;
    private javax.swing.JLabel dbLabel1;
    private javax.swing.JLabel dbLabel2;
    private javax.swing.JLabel dbLabel3;
    private javax.swing.JLabel dbLabel4;
    private javax.swing.JLabel dbLabel5;
    private javax.swing.JLabel dbLabel6;
    private javax.swing.JLabel dbLabel7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    public static javax.swing.JTable jTable2;
    public javax.swing.JPanel winTab1;
    public javax.swing.JPanel winTab2;
    public javax.swing.JPanel winTab3;
    public javax.swing.JPanel winTab4;
    public javax.swing.JPanel winTab5;
    public javax.swing.JPanel winTab6;
    // End of variables declaration//GEN-END:variables
}
