/*
 * The MIT License
 *
 * Copyright 2023 Pedj.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package libsys.views;

import javax.swing.JOptionPane;
import libsys.controllers.UserInfoController;

/**
 *
 * @author Pedj
 */
public class UserInfo extends javax.swing.JFrame {

    public String userIDString;
    public String userNameString;
    public String userEmailString;
    public static String borrowIDString;
    public static String bookIDString;
    public static int bookQtyInt;

    /**
     * Creates new form UserInfoWindow
     */
    public UserInfo() {
        initComponents();
        initUserInfo();
    }

    public UserInfo(String userIDString, String userNameString, String userEmailString) {
        if (userIDString == null || userNameString == null || userEmailString == null) {
            return;
        }

        this.userIDString = userIDString;
        this.userNameString = userNameString;
        this.userEmailString = userEmailString;
        initComponents();
        initUserInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userInfoTable = new javax.swing.JTable();
        userSearchField = new javax.swing.JTextField();
        userPaidBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userIDLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        userEmailLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        userPaymentLabel = new javax.swing.JLabel();
        userPaymentLabel1 = new javax.swing.JLabel();
        userPaymentLabel2 = new javax.swing.JLabel();
        userBDLabel = new javax.swing.JLabel();
        userRDLabel = new javax.swing.JLabel();
        userTDLabel = new javax.swing.JLabel();
        userAddBtn = new javax.swing.JButton();
        userRefreshBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Information");
        setMinimumSize(new java.awt.Dimension(1000, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 510));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 510));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(userInfoTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 740, 320));

        userSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSearchFieldActionPerformed(evt);
            }
        });
        jPanel1.add(userSearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 440, -1));

        userPaidBtn.setBackground(new java.awt.Color(153, 153, 255));
        userPaidBtn.setText("Paid");
        userPaidBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPaidBtnActionPerformed(evt);
            }
        });
        jPanel1.add(userPaidBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, 200, 40));

        jLabel1.setText("User ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jLabel2.setText("User Email:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, 20));

        jLabel3.setText("User Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 20));

        userIDLabel.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.add(userIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 380, 20));

        userNameLabel.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 380, 20));

        userEmailLabel.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.add(userEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 380, 20));

        jLabel4.setText("Borrow Record:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, -1));

        jLabel5.setText("Payment:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 210, -1));

        jLabel6.setText("Borrowed Date:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 210, -1));

        jLabel7.setText("Today:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, 210, 20));

        jLabel8.setText("Search :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 50, -1));

        jLabel9.setText("Returned Date:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 210, -1));
        jPanel1.add(userPaymentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 150, 20));
        jPanel1.add(userPaymentLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 150, 20));
        jPanel1.add(userPaymentLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, 150, 20));
        jPanel1.add(userBDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 150, 20));
        jPanel1.add(userRDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 150, 20));
        jPanel1.add(userTDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 290, 150, 20));

        userAddBtn.setBackground(new java.awt.Color(153, 255, 153));
        userAddBtn.setText("New Borrow");
        userAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAddBtnActionPerformed(evt);
            }
        });
        jPanel1.add(userAddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 110, 40));

        userRefreshBtn.setBackground(new java.awt.Color(255, 255, 153));
        userRefreshBtn.setText("Refresh");
        userRefreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userRefreshBtnActionPerformed(evt);
            }
        });
        jPanel1.add(userRefreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void initUserInfo() {
        userIDLabel.setText(userIDString);
        userNameLabel.setText(userNameString);
        userEmailLabel.setText(userEmailString);
        UserInfoController.loadUserInfoTable(jScrollPane1, userIDString);

    }

    private void userPaidBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPaidBtnActionPerformed
        // TODO add your handling code here:
        String borrowID = borrowIDString;

        // Perform checks if necessary before updating isReturned
        if (borrowID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select from table.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        UserInfoController.updateIsReturned(borrowID);
    }//GEN-LAST:event_userPaidBtnActionPerformed

    private void userSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userSearchFieldActionPerformed

    private void userAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAddBtnActionPerformed
        // TODO add your handling code here:
        if (userIDString.isEmpty() || userIDString == null) {
            return;
        }
        BNRWindow bnrw = new BNRWindow(userIDString);
        bnrw.setVisible(true);

        bnrw.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_userAddBtnActionPerformed

    private void userRefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userRefreshBtnActionPerformed
        // TODO add your handling code here:
        UserInfoController.refreshTableModel(jScrollPane1, userIDString);
    }//GEN-LAST:event_userRefreshBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton userAddBtn;
    public static javax.swing.JLabel userBDLabel;
    private javax.swing.JLabel userEmailLabel;
    private javax.swing.JLabel userIDLabel;
    private javax.swing.JTable userInfoTable;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JButton userPaidBtn;
    public static javax.swing.JLabel userPaymentLabel;
    public static javax.swing.JLabel userPaymentLabel1;
    public static javax.swing.JLabel userPaymentLabel2;
    public static javax.swing.JLabel userRDLabel;
    private javax.swing.JButton userRefreshBtn;
    public static javax.swing.JTextField userSearchField;
    public static javax.swing.JLabel userTDLabel;
    // End of variables declaration//GEN-END:variables
}
